name: TEST
on:
  pull_request:
    branches:
      - main
env: 
  PASSWORD: NEZNAM
jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      USER: FILIP
    steps:
    - name: Test-step
      uses: ./.github/actions/action.yaml