name: TEST
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env: 
  PASSWORD: NEZNAM
jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      USER: FILIP
    steps:      
    - name: Checkout
      uses: actions/checkout@v3.1.0
      
    - name: Test-step
      uses: ./.github/workflows/action.yaml