apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-deployment
  namespace: argocd
  labels:
    name: argo-workflows-deployment
spec:
  project: default
  source:
    repoURL: https://github.com/filipjosifoski/argo-test.git  # Can point to either a Helm chart repo or a git repo.
    targetRevision: HEAD
    path: argoworkflows/deployment
  destination:
    namespace: argo-workflows
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

